[package]
name = "tplug-common"
version = "0.1.0"
edition = "2021"

[dependencies]
tplug-macros = { path = "../tplug-macros" }
log.workspace = true
# semver = "1.0.25"

[features]
default = []
plugin = []
plugin-manager = []
