[package]
name = "tplug-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tplug-common = { path = "../tplug-common", features = ["plugin"] }
log.workspace = true
thiserror.workspace = true
