[workspace]
resolver = "2"
members = ["tplug-common", "tplug"]

[workspace.dependencies]
log = "0.4.22"

[profile.release]
opt-level = "s"
strip = true
lto = true
codegen-units = 1
split-debuginfo = "off"
