[package]
name = "tplug"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
colog = "1.3.0"
libloading = "0.8.6"
tplug-common = { path = "../tplug-common", features = ["plugin-manager"] }
log.workspace = true
