[package]
name = "tplug"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
env_logger = "0.11.6"
libloading = "0.8.6"
log.workspace = true
tplug-common = { path = "../tplug-common" }
